// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClaudeHome() {
  return window['go']['services']['ConfigService']['GetClaudeHome']();
}

export function GetGlobalConfig() {
  return window['go']['services']['ConfigService']['GetGlobalConfig']();
}

export function GetProjectConfig(arg1) {
  return window['go']['services']['ConfigService']['GetProjectConfig'](arg1);
}

export function SaveGlobalClaudeMd(arg1) {
  return window['go']['services']['ConfigService']['SaveGlobalClaudeMd'](arg1);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['services']['ConfigService']['SaveGlobalSettings'](arg1);
}

export function SaveProjectClaudeMd(arg1, arg2) {
  return window['go']['services']['ConfigService']['SaveProjectClaudeMd'](arg1, arg2);
}

export function SaveProjectMcp(arg1, arg2) {
  return window['go']['services']['ConfigService']['SaveProjectMcp'](arg1, arg2);
}

export function SaveProjectSettings(arg1, arg2) {
  return window['go']['services']['ConfigService']['SaveProjectSettings'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['services']['ConfigService']['SelectDirectory']();
}

export function SetContext(arg1) {
  return window['go']['services']['ConfigService']['SetContext'](arg1);
}
