// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetClaudeHome():Promise<string>;

export function GetGlobalConfig():Promise<services.GlobalConfig>;

export function GetProjectConfig(arg1:string):Promise<services.ProjectConfig>;

export function SaveGlobalClaudeMd(arg1:string):Promise<void>;

export function SaveGlobalSettings(arg1:string):Promise<void>;

export function SaveProjectClaudeMd(arg1:string,arg2:string):Promise<void>;

export function SaveProjectMcp(arg1:string,arg2:string):Promise<void>;

export function SaveProjectSettings(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
