// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExportGlobalConfig():Promise<string>;

export function ExportProjectConfig(arg1:string):Promise<string>;

export function ImportConfig(arg1:string):Promise<number>;

export function ImportGlobalConfig():Promise<number>;

export function ImportProjectConfig(arg1:string):Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;
