// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportGlobalConfig() {
  return window['go']['services']['ExportService']['ExportGlobalConfig']();
}

export function ExportProjectConfig(arg1) {
  return window['go']['services']['ExportService']['ExportProjectConfig'](arg1);
}

export function ImportConfig(arg1) {
  return window['go']['services']['ExportService']['ImportConfig'](arg1);
}

export function ImportGlobalConfig() {
  return window['go']['services']['ExportService']['ImportGlobalConfig']();
}

export function ImportProjectConfig(arg1) {
  return window['go']['services']['ExportService']['ImportProjectConfig'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['ExportService']['SetContext'](arg1);
}
