// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteExtension(arg1, arg2, arg3) {
  return window['go']['services']['ExtensionService']['DeleteExtension'](arg1, arg2, arg3);
}

export function GetExtension(arg1, arg2, arg3) {
  return window['go']['services']['ExtensionService']['GetExtension'](arg1, arg2, arg3);
}

export function InstallOnlineExtension(arg1, arg2, arg3) {
  return window['go']['services']['ExtensionService']['InstallOnlineExtension'](arg1, arg2, arg3);
}

export function ListExtensions(arg1, arg2) {
  return window['go']['services']['ExtensionService']['ListExtensions'](arg1, arg2);
}

export function RenameExtension(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ExtensionService']['RenameExtension'](arg1, arg2, arg3, arg4);
}

export function SaveExtension(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ExtensionService']['SaveExtension'](arg1, arg2, arg3, arg4);
}

export function SearchOnlineExtensions(arg1, arg2, arg3) {
  return window['go']['services']['ExtensionService']['SearchOnlineExtensions'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['ExtensionService']['SetContext'](arg1);
}
