// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function DeleteExtension(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetExtension(arg1:string,arg2:string,arg3:string):Promise<services.ExtensionFile>;

export function InstallOnlineExtension(arg1:string,arg2:services.OnlineExtension,arg3:string):Promise<void>;

export function ListExtensions(arg1:string,arg2:string):Promise<Array<services.ExtensionFile>>;

export function RenameExtension(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveExtension(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SearchOnlineExtensions(arg1:string,arg2:string,arg3:string):Promise<services.OnlineExtensionResult>;

export function SetContext(arg1:context.Context):Promise<void>;
