// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalHooks() {
  return window['go']['services']['HooksService']['GetGlobalHooks']();
}

export function GetProjectHooks(arg1) {
  return window['go']['services']['HooksService']['GetProjectHooks'](arg1);
}

export function SaveGlobalHooks(arg1) {
  return window['go']['services']['HooksService']['SaveGlobalHooks'](arg1);
}

export function SaveProjectHooks(arg1, arg2) {
  return window['go']['services']['HooksService']['SaveProjectHooks'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['HooksService']['SetContext'](arg1);
}
