// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetGlobalHooks():Promise<Array<services.HooksConfig>>;

export function GetProjectHooks(arg1:string):Promise<Array<services.HooksConfig>>;

export function SaveGlobalHooks(arg1:Array<services.HooksConfig>):Promise<void>;

export function SaveProjectHooks(arg1:string,arg2:Array<services.HooksConfig>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
