// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalMCPServers() {
  return window['go']['services']['MCPService']['GetGlobalMCPServers']();
}

export function GetProjectMCPServers(arg1) {
  return window['go']['services']['MCPService']['GetProjectMCPServers'](arg1);
}

export function InstallFromMarketplace(arg1, arg2) {
  return window['go']['services']['MCPService']['InstallFromMarketplace'](arg1, arg2);
}

export function SaveGlobalMCPServers(arg1) {
  return window['go']['services']['MCPService']['SaveGlobalMCPServers'](arg1);
}

export function SaveProjectMCPServers(arg1, arg2) {
  return window['go']['services']['MCPService']['SaveProjectMCPServers'](arg1, arg2);
}

export function SearchMarketplace(arg1, arg2, arg3) {
  return window['go']['services']['MCPService']['SearchMarketplace'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['services']['MCPService']['SetContext'](arg1);
}
