// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetGlobalMCPServers():Promise<Array<services.MCPServer>>;

export function GetProjectMCPServers(arg1:string):Promise<Array<services.MCPServer>>;

export function InstallFromMarketplace(arg1:string,arg2:string):Promise<void>;

export function SaveGlobalMCPServers(arg1:Array<services.MCPServer>):Promise<void>;

export function SaveProjectMCPServers(arg1:string,arg2:Array<services.MCPServer>):Promise<void>;

export function SearchMarketplace(arg1:string,arg2:string,arg3:string):Promise<services.MarketplaceResult>;

export function SetContext(arg1:context.Context):Promise<void>;
