// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnabledPlugins() {
  return window['go']['services']['PluginService']['GetEnabledPlugins']();
}

export function GetInstalledPlugins() {
  return window['go']['services']['PluginService']['GetInstalledPlugins']();
}

export function SetContext(arg1) {
  return window['go']['services']['PluginService']['SetContext'](arg1);
}

export function TogglePlugin(arg1, arg2) {
  return window['go']['services']['PluginService']['TogglePlugin'](arg1, arg2);
}
