// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetEnabledPlugins():Promise<Array<services.PluginInfo>>;

export function GetInstalledPlugins():Promise<Array<services.PluginInfo>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TogglePlugin(arg1:string,arg2:boolean):Promise<void>;
