// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalStats() {
  return window['go']['services']['ProjectService']['GetGlobalStats']();
}

export function GetProjectDetail(arg1) {
  return window['go']['services']['ProjectService']['GetProjectDetail'](arg1);
}

export function InitProjectConfig(arg1) {
  return window['go']['services']['ProjectService']['InitProjectConfig'](arg1);
}

export function ScanProjects() {
  return window['go']['services']['ProjectService']['ScanProjects']();
}

export function SetContext(arg1) {
  return window['go']['services']['ProjectService']['SetContext'](arg1);
}
