// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function GetGlobalStats():Promise<Record<string, any>>;

export function GetProjectDetail(arg1:string):Promise<services.ProjectInfo>;

export function InitProjectConfig(arg1:string):Promise<void>;

export function ScanProjects():Promise<Array<services.ProjectInfo>>;

export function SetContext(arg1:context.Context):Promise<void>;
