// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSkillFile(arg1, arg2, arg3) {
  return window['go']['services']['SkillService']['CreateSkillFile'](arg1, arg2, arg3);
}

export function DeleteSkillFile(arg1, arg2, arg3) {
  return window['go']['services']['SkillService']['DeleteSkillFile'](arg1, arg2, arg3);
}

export function DeleteUserSkill(arg1, arg2, arg3) {
  return window['go']['services']['SkillService']['DeleteUserSkill'](arg1, arg2, arg3);
}

export function GetAllSkills() {
  return window['go']['services']['SkillService']['GetAllSkills']();
}

export function GetMCPServerNames() {
  return window['go']['services']['SkillService']['GetMCPServerNames']();
}

export function GetSkillContent(arg1) {
  return window['go']['services']['SkillService']['GetSkillContent'](arg1);
}

export function GetUserSkill(arg1, arg2) {
  return window['go']['services']['SkillService']['GetUserSkill'](arg1, arg2);
}

export function ListSkillFiles(arg1, arg2) {
  return window['go']['services']['SkillService']['ListSkillFiles'](arg1, arg2);
}

export function ListUserSkills(arg1) {
  return window['go']['services']['SkillService']['ListUserSkills'](arg1);
}

export function ReadSkillFile(arg1, arg2, arg3) {
  return window['go']['services']['SkillService']['ReadSkillFile'](arg1, arg2, arg3);
}

export function SaveSkillFile(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SkillService']['SaveSkillFile'](arg1, arg2, arg3, arg4);
}

export function SaveUserSkill(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['SkillService']['SaveUserSkill'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetContext(arg1) {
  return window['go']['services']['SkillService']['SetContext'](arg1);
}
