// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreateSkillFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSkillFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteUserSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllSkills():Promise<Array<services.SkillInfo>>;

export function GetMCPServerNames():Promise<Array<string>>;

export function GetSkillContent(arg1:string):Promise<string>;

export function GetUserSkill(arg1:string,arg2:string):Promise<Record<string, string>>;

export function ListSkillFiles(arg1:string,arg2:string):Promise<Array<services.SkillFileInfo>>;

export function ListUserSkills(arg1:string):Promise<Array<services.UserSkillInfo>>;

export function ReadSkillFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveSkillFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveUserSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
