// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTemplate(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['ApplyTemplate'](arg1, arg2, arg3);
}

export function GetInstalledTemplates(arg1, arg2) {
  return window['go']['services']['TemplateService']['GetInstalledTemplates'](arg1, arg2);
}

export function GetTemplateByID(arg1) {
  return window['go']['services']['TemplateService']['GetTemplateByID'](arg1);
}

export function GetTemplates() {
  return window['go']['services']['TemplateService']['GetTemplates']();
}

export function InstallTemplateRules(arg1, arg2, arg3, arg4) {
  return window['go']['services']['TemplateService']['InstallTemplateRules'](arg1, arg2, arg3, arg4);
}

export function MigrateFlatSkills(arg1) {
  return window['go']['services']['TemplateService']['MigrateFlatSkills'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['TemplateService']['SetContext'](arg1);
}

export function UninstallTemplateRules(arg1, arg2, arg3) {
  return window['go']['services']['TemplateService']['UninstallTemplateRules'](arg1, arg2, arg3);
}
