// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {templatedata} from '../models';
import {context} from '../models';

export function ApplyTemplate(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GetInstalledTemplates(arg1:string,arg2:string):Promise<Array<templatedata.InstalledTemplateInfo>>;

export function GetTemplateByID(arg1:string):Promise<templatedata.Template>;

export function GetTemplates():Promise<Array<templatedata.TemplateCategory>>;

export function InstallTemplateRules(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<void>;

export function MigrateFlatSkills(arg1:string):Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UninstallTemplateRules(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
